# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Excutable
        run: dotnet build --no-restore
      - name: Extract Input from 7z Archive
        env:
          ARCHIVE_PASSWORD: ${{ secrets.ARCHIVEPASSWORD }}
        run: |
          # Save the current directory
          set ORIGINAL_DIR=%CD%
          
          # Navigate to the target directory
          cd AdventOfCode.Solutions\Inputs
          
          # Extract the 7z archive
          7z x .\Input.7z -p"%ARCHIVE_PASSWORD%" 
          
          # Return to the original directory
          cd %ORIGINAL_DIR%
      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal